tiny_50mb:
  hnsw: {M: 12, efc: 200, ef: 64}
  ivfpq: {nlist: "auto", m: 16, bits: 8, opq: false, nprobe: 8}
  flatpq: {m: 16, bits: 8}

mid_100mb:
  hnsw: {M: 24, efc: 200, ef: 128}
  ivfpq: {nlist: "auto", m: 32, bits: 8, opq: true, nprobe: 16}
  flatpq: {m: 32, bits: 8}

max_150mb:
  hnsw: {M: 32, efc: 200, ef: 128}
  ivfpq: {nlist: "auto", m: 32, bits: 8, opq: true, nprobe: 32}
  flatpq: {m: 32, bits: 8}
